/* Chapter 11 */
(function(){
  var S=[
    {t:"Step 0: call an LLM",d:"The starting point is the plain \"hello world\" chat call: send a message, get text back. There is no agent yet.",c:"reply = call_llm([user_message])\nprint(reply)"},
    {t:"Step 1: a condition (is it done?)",d:"After the model answers, make a second call that acts as a strict critic (an LLM judge). Ask: does this answer completely respond to the question? Force the reply into strict JSON, for example {\"done\": true}. The demo question was \"What is the average wing speed of a swallow?\". So far it still feels deterministic and mechanical.",c:"answer = call_llm([question])\nverdict = call_llm([\"Strict critic: is this a complete answer? Reply JSON {\\\"done\\\": bool}\", question, answer])\nif verdict[\"done\"]:\n    return answer"},
    {t:"Step 2: tools",d:"Add a web search tool. You describe the tool to the model with a name, a description, and a JSON schema for its parameters (here a query and a location). The model returns <i>which tool to call and with what arguments</i>. The SDK does not run it. <b>Your code must.</b> Then you send both the tool call and its result back into the conversation and call the model again. The model may call tools several times in an inner loop until it is satisfied. In the demo a call failed because the model passed a location the API's validation rejected. Lesson: validate arguments, and return errors as results.",c:"reply = call_llm(messages, tools=[search_spec])\nfor call in reply.tool_calls:\n    result = TOOLS[call.name](**call.arguments)   # your code runs it\n    messages += [call, result]                    # send both back\nreply = call_llm(messages, tools=[search_spec])  # model continues"},
    {t:"Step 3: parallel tool calls",d:"A model can ask for several tool calls in one turn, for example three searches at once. You run each, and send each result back with the <b>tool-call ID</b> so the model can match request and response. Sometimes it calls the same tool several times with different inputs. A small refactor moves the tool code into its own file.",c:"for call in reply.tool_calls:                 # maybe several at once\n    result = TOOLS[call.name](**call.arguments)\n    messages.append({\"tool_call_id\": call.id, \"content\": result})"},
    {t:"Step 4: planning with a to-do list",d:"The big change. Give the agent tools to <b>add</b> to-do items, <b>mark them done</b>, and <b>check what is pending</b>. The system prompt says: before any work, always make a plan with your to-do list, cross items off as you complete them, then summarise and report. This covers planning and read/write memory. Even the done-check becomes a tool, so the loop is run by the model itself. Lasater then asks it to plan a date night and watches it plan, search, browse and tick things off. This is where it starts to feel like an agent.",c:"TOOLS = {\"add_todo\":..., \"complete_todo\":..., \"list_todo\":...,\n         \"search\":..., \"browse\":..., \"check_goal_done\":...}\nsystem = \"Always plan with your to-do list first. Report when finished.\""}
  ];
  H.stepper($("#bd-step"),S,function(s,i,body){
    body.innerHTML="<p style='margin:.3rem 0'><b>"+esc(s.t)+"</b></p><p style='margin:.3rem 0'>"+s.d+"</p><div class='pre-out'>"+esc(s.c)+"</div>";
  });
})();

Q.c11=[
  {q:"In a tool-calling loop, who actually executes the tool?",o:["The model","Your code, which then sends the result back to the model","The API provider, automatically"],a:1,f:"The SDK returns which tool and arguments the model wants. Your code runs it and sends both the call and the result back."},
  {q:"Why must tool results carry the tool-call ID when several tools are called in parallel?",o:["It makes them faster","So the model can match each result to the request that produced it","It is just a habit"],a:1,f:"Without the ID the model cannot tell which result belongs to which call."},
  {q:"What did adding a to-do list (step 4) add to the agent?",o:["Planning and a place to read and write state","A larger model","Faster typing"],a:0,f:"It gives the agent a plan it can follow and update, which is the main shift toward agent-like behaviour."},
  {q:"Which is NOT a good safety rail for an agent loop?",o:["A maximum number of steps","Logging every step","Running model-written text with eval() so it is flexible"],a:2,f:"Never run model output as code directly. Parse and validate it, and keep tools narrow."},
  {q:"Which statement about frameworks is best?",o:["They replace the need to understand the loop","They add convenience such as persistence, retries and observability on top of the same basic loop","They do not use loops"],a:1,f:"Understand the raw loop first. Frameworks wrap it."}
];
